name: Build release package
on:
  schedule:
    - cron: "00 20 * * *"
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "current_date=$(date "+%Y%m%d")" >> "$GITHUB_ENV"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Fetch clash config
        run: |
          python -m pip install --upgrade pip
          pip install wget pyyaml
          python ./main.py
          gh release create "$(date "+%Y%m%d")" MyClash.yml
