name: Build release package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "current_date=$(date "+%Y%m%d")" >> "$GITHUB_ENV"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wget pyyaml==6.0
      - name: Fetch clash config
        run: python ./main.py
      - name: Create Release
        id: create-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.current_date }}
          release_name: ${{ env.current_date }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./myfiles/MyClash.yml
          asset_name: MyClash.yml
          asset_content_type: text/vnd.yml
