name: Build release package
on:
  schedule:
    - cron: "00 20 * * *"
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.0
      - name: Fetch clash config
        run: |
          curl -sLO https://github.com/chise0713/warp-reg.sh/raw/master/warp-reg.sh
          bash warp-reg.sh
          reg() {
              set -e
              keypair=$(openssl genpkey -algorithm X25519|openssl pkey -text -noout)
              private_key=$(echo "$keypair" | awk '/priv:/{flag=1; next} /pub:/{flag=0} flag' | tr -d '[:space:]' | xxd -r -p | base64)
              public_key=$(echo "$keypair" | awk '/pub:/{flag=1} flag' | tr -d '[:space:]' | xxd -r -p | base64)
              curl -X POST 'https://api.cloudflareclient.com/v0a2158/reg' -sL --tlsv1.3 \
              -H 'CF-Client-Version: a-7.21-0721' -H 'Content-Type: application/json' \
              -d \
             '{
                  "key":"'${public_key}'",
                  "tos":"'$(date +"%Y-%m-%dT%H:%M:%S.000Z")'"
              }' \
                  | ${jq} | sed "/\"account_type\"/i\         \"private_key\": \"$private_key\","
          }
          reg
          python -m pip install --upgrade pip
          pip install wget pyyaml
          python ./main.py
          gh release create "$(date "+%Y%m%d%H%M%S")" --generate-notes MyClash.yml
